### ISSUE TITLE
Fails to Start Fetching on IE7 and IE8

### ISSUE THREAD

**Issue by azer** [staugaard/ember-resource#26]
It actually seems like an Ember bug. It doesn't start fetching on IE7 and IE8.

Follow the steps below to reprod the issue:
1. wget https://github.com/downloads/azer/ember-resource/sc-resource-fetch-bug.tar.gz 
2. tar xvvf sc-resource-fetch-bug.tar.gz & cd sc-resource-fetch-bug
3. make publish
4. open http://localhost:8000 with a modern browser
5. make sure that a request has been sent to "/node/$subdomain/api/v2/users/3". Ignore the 404 error.
6. open same URL with IE7 or IE8
7. Monitor the network activities using Fiddler or the output of "make publish"
8. IE7 and IE8 doesn't send any request to the resource URL.

**Comment by staugaard** [comment]
This works just fine using the newest version of ember-resource
