### ISSUE TITLE
Does ember-resource support Ember's computed properties?

### ISSUE THREAD

**Issue by sohara** [staugaard/ember-resource#27]
Hi there,
I've been trying out ember-resource and it seems to break the computer property functions I previously had in my classes (which were regular Ember.Objects previous to trying ember-resource). 

Here's an example of what I'm trying to do: 
http://jsfiddle.net/sohara/wqhwn/8/

Is this not supported? Or is there a different way of defining computed properties within an Ember.Resource?
Thanks,
Sean

**Comment by staugaard** [comment]
You can not define computed properties inside the `define` block.

You need to reopen the class like I've done here:
http://jsfiddle.net/wqhwn/9/

On Mon, Jan 16, 2012 at 12:09, Sean O'Hara <
reply@reply.github.com
