### ISSUE TITLE
Doing ToDo example using sproutcore-resource

### ISSUE THREAD

**Issue by whump** [staugaard/ember-resource#8]
https://gist.github.com/1190141

Is this gist the right approach to use here?

**Comment by staugaard** [comment]
I wrote a little stupid example in the readme now, but please keep the questions coming.

**Comment by staugaard** [comment]
Hope this helps you: https://github.com/staugaard/sproutcore-resource-todos

**Comment by whump** [comment]
On Sep 4, 2011, at 12:17 AM, staugaard wrote:

> Hope this helps you: https://github.com/staugaard/sproutcore-resource-todos

Yes, this is very similar to what I got to friday evening, but I was using a static JSON file. 

Thanks!

-- whump
