### ISSUE TITLE
Partial Load Cascades to Fetch

### ISSUE THREAD

**Issue by jamesarosen** [staugaard/ember-resource#9]
Given a resource with two properties and a third that depends on the first two, if you create an instance with one but not the other, the full resource will be fetched even if no client ever asks for the dependent property. For example:

``` javascript
MyModel = SC.Resource.define({
  schema: {
    foo: String,
    bar: String
  }
}).extend({
  baz: function()  {
    return this.get('foo') + this.get('bar');
  }).property('foo', 'bar').cacheable()
});

aModel = MyModel.create({ id: 12, foo: 'FOO' });
```

Immediately after that last line, Sproutcore notifies the model that `foo` changed (from `undefined` to `FOO`), which causes `baz` to be recalculated, which causes `bar` to be requested, which causes the model to be fetched.

The correct behavior is that only if an outside client (e.g. a view) requests `bar` or `baz` does the model get fetched.

**Comment by jamesarosen** [comment]
Some have asked about the use case for the "correct behavior" as described above. Imagine you have an API endpoint that returns summary information for a large number of `MyModel` objects -- just `id` and `foo` -- and a view that renders that collection. Simply rendering the collection will cause n+1 API lookups even though you just need the summary information (at least until you click on one to dig in).

**Comment by jamesarosen** [comment]
If we were to use `setAttribute` in the initial construction, then it's true that the dependent property observers would not fire, and thus not cause a fetch. Unfortunately, it also means that nothing else watching the properties we set would update either.

**Comment by jamesarosen** [comment]
Essentially the crux of the problem is: can we circumvent the dependent property system without circumventing other observers?

**Comment by jamesarosen** [comment]
Sproutcore's dependent properties don't get run unless they're asked for: http://jsfiddle.net/tf5Pj/

I think this is a non-issue. Perhaps we're actually asking for `baz` somewhere?

**Comment by jamesarosen** [comment]
We _are_ still seeing an issue here, but it's not what I've described above. The problem is that when constructing each `MyModel` element in the collection, Sproutcore calls `rewatch` to set up the bindings. Unfortunately, it does that _before_ `data` is set on the object, so any chains called from `rewatch` will cause a fetch when they look for the nonexistent data.

One solution would be to put the model in a "constructing" state as soon as it's created -- even before calling super -- and not doing fetches in that state.

**Comment by jamesarosen** [comment]
Making the following change to `propertyFunction` seems to fix the problem, but I can't figure out how to test it:

Before:

``` javascript
if (serializedValue === undefined) {
```

After:

``` javascript
if (serializedValue === undefined && this.get('resourceState') !== SC.Resource.Lifecycle.INITIALIZING) {
```

**Comment by staugaard** [comment]
Thanks James. Much has changed in SC.Resource since this issue, and this should no longer be a problem. Fetched never happen during initialization.
